- Verwaltung:
    - Fritzbox:
        - href: http://fritz.box
    - Fritzbox extern:
        - href: https://14fgwxfa0pcyfqpn.myfritz.net:49284
    - Mailbox.org:
        - href: https://login.mailbox.org
