- resources:
    label: System
    cpu: true
    memory: true
    disk: /app/config
    diskUnits: gigabytes

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: short
      hourCycle: h23
